### ISSUE TITLE
add missing hardware

### ISSUE THREAD

**Issue by butlerx** [redbrick/docs-old#1]
- [x] paphos
- [x] zeus
- [x] pygmalion
- [x] albus
- [x] halfpint

**Comment by VoyTechnology** [comment]
Azazel added in  commit 3f6a354f2051db3a4fde32367568f3614512d1d9

**Comment by gruunday** [comment]
Paphos added in commit b09edae

**Comment by butlerx** [comment]
zeus and pyg have been added but the info isnt complete

**Comment by theycallmemac** [comment]
How are we looking on this issue? If it near closure yet?

**Comment by butlerx** [comment]
daedalus and icarus now need to be added and i believe the service list on zeus needs to be updated

**Comment by theycallmemac** [comment]
Okay thanks :)

**Comment by m1cr0man** [comment]
Daedalus and Icarus are now done

**Comment by butlerx** [comment]
Hardcase needs to be added

**Comment by theycallmemac** [comment]
Hardcase has been added and the zeus list updated so we can close this now :)

**Comment by m1cr0man** [comment]
Actually, no. I still need to doc the new UPS :P
