### ISSUE TITLE
Update **New Install** procedure

### ISSUE THREAD

**Issue by butlerx** [redbrick/docs-old#139]
https://github.com/redbrick/docs/blob/master/docs/procedures/newinstalls.md 
these docs are based on ubuntu 14.04 and now very defunct 
They should be replaced with docs processing spinning up nixos machine
- including steps on installing nixos
- adding machine to nix-config
- adding services

cc @m1cr0man

**Comment by m1cr0man** [comment]
Done, when I did metharme. I'll commit it this weekend

**Comment by m1cr0man** [comment]
Closed with #146
