### ISSUE TITLE
add monitoring docs

### ISSUE THREAD

**Issue by butlerx** [redbrick/docs-old#2]
- [ ] grafana
- [ ] prometheus
- [ ] collectd

**Comment by theycallmemac** [comment]
This stack doesn't actually exist in Redbrick anymore, this should probably be moved to legacy

**Comment by butlerx** [comment]
Let's just update the list to be
- [ ] telegraph 
- [ ] influx 
- [ ] chronograph. 

I believe @m1cr0man is planing to keep grafana also

**Comment by theycallmemac** [comment]
I'll get the list updated - but I won't add any Grafana stuff as it doesnt make up the current stack at the moment.

**Comment by butlerx** [comment]
the stack exists again. in the form of grafana, prometheus, node-exporter, and loki
