### ISSUE TITLE
formatting error on backuppc docs

### ISSUE THREAD

**Issue by butlerx** [redbrick/docs-old#24]
the backuppc docs code block is formatted odd
http://redbrick.readthedocs.io/en/master/services/backuppc/

**Comment by zergless** [comment]
What do you want changed?

**Comment by VoyTechnology** [comment]
https://docs.redbrick.dcu.ie/services/backuppc/
- The command block looks bad
- Add title maybe?

**Comment by butlerx** [comment]
its weird as the markdown seems fine in github https://github.com/redbrick/docs/blob/master/docs/services/backuppc.md

**Comment by VoyTechnology** [comment]
While we are at the doc, we should replace the [here] link with [Backuppc Documentation]

**Comment by VoyTechnology** [comment]
Fix in #31
