### ISSUE TITLE
CircleCI doesn't fail despite tests failing

### ISSUE THREAD

**Issue by VoyTechnology** [redbrick/docs-old#25]
Make sure the change doesn't break any existing pages by adding a link checker to the CircleCI.

This possibly should be optional at first until we fix all currently broken links.

**Comment by butlerx** [comment]
we have one 
change to fix

**Comment by butlerx** [comment]
it appears to not test anyfiles
also there are no broken links until #12 was merged as i fixed them in 15114c7cf163f7280e415bfffcee458d83b66f1b

**Comment by VoyTechnology** [comment]
Oops, this is still ongoing

**Comment by VoyTechnology** [comment]
@butlerx any updates?

**Comment by butlerx** [comment]
see [here](https://github.com/redbrick/static-site/blob/master/.circleci/config.yml) for how to do test properly

**Comment by butlerx** [comment]
no longer a issue
