### ISSUE TITLE
Add Makefile

### ISSUE THREAD

**Issue by VoyTechnology** [redbrick/docs-old#36]
While docker compose is all nice and good, its an unnecessary dependency if the repo needs to be edited on the fly. We should have a simple Makefile to build the docker container and test.

For context: Was doing a change on RPI and had to set the entire environment up.

**Comment by butlerx** [comment]
not that i'm opposed to a makefile but i dont see what it could give us over what we already have if it was just going to build a docker container except being a wrapper for docker compose.

**Comment by VoyTechnology** [comment]
The idea was to have it on devices which have potential problems with docker, such as RPi

**Comment by butlerx** [comment]
just add docs about `pip install -r requirment.txt` and `mkdocs serve/build`
