### ISSUE TITLE
blank pages at the following

### ISSUE THREAD

**Issue by zergless** [redbrick/docs-old#7]
https://docs.redbrick.dcu.ie/network/higgs/
https://docs.redbrick.dcu.ie/network/bind9/
https://docs.redbrick.dcu.ie/network/hadron/
https://docs.redbrick.dcu.ie/network/junos/
https://docs.redbrick.dcu.ie/web/apache24/
https://docs.redbrick.dcu.ie/procedures/gpgkeys/ 
https://docs.redbrick.dcu.ie/procedures/pwsafe/ 
https://docs.redbrick.dcu.ie/procedures/useradm/
https://docs.redbrick.dcu.ie/machines/paphos/  
https://docs.redbrick.dcu.ie/machines/pygmalion/ 
https://docs.redbrick.dcu.ie/machines/zeus/

**Comment by VoyTechnology** [comment]
On a side note, is `bind9` really a network thing or rather a service (internal, but still a service)

**Comment by zergless** [comment]
Probably better off in services tbh.

**Comment by butlerx** [comment]
closeing as added to #4 #5 #6
