### ISSUE TITLE
Add NickServ IRC links

### ISSUE THREAD

**Issue by VoyTechnology** [redbrick/docs-old#85]
We currently have no documentation in the [IRC Operations](https://docs.redbrick.dcu.ie/procedures/irc_operator/) guide on how to manage NickServ, especially changing passwords for users.

**Comment by butlerx** [comment]
that's because we don't manage nickserv

**Comment by VoyTechnology** [comment]
This is fine. We should have at least a link to the place we can get documentation for it.

**Comment by butlerx** [comment]
......we dont run nickserv there so why would we be changing passwords on it

**Comment by VoyTechnology** [comment]
Can this at least be discussed as opposed to constantly closing the issue.

**Comment by VoyTechnology** [comment]
If our user requests a password change for NickServ, what do we do. This should be mentioned in the IRC Operator docs.

**Comment by CSmartt** [comment]
`13:42 -- MSG(nickserv): HELP
13:42 -- NickServ (services@anope-services.intersocs): NickServ allows you to "register" a nickname and
13:42 -- NickServ (services@anope-services.intersocs): prevent others from using it. The following
13:42 -- NickServ (services@anope-services.intersocs): commands allow for registration and maintenance of
13:42 -- NickServ (services@anope-services.intersocs): nicknames; to use them, type /msg NickServ command.
13:42 -- NickServ (services@anope-services.intersocs): For more information on a specific command, type
13:42 -- NickServ (services@anope-services.intersocs): /msg NickServ HELP command.
13:42 -- NickServ (services@anope-services.intersocs):  
13:42 -- NickServ (services@anope-services.intersocs):     REGISTER   Register a nickname
13:42 -- NickServ (services@anope-services.intersocs):     GROUP      Join a group
13:42 -- NickServ (services@anope-services.intersocs):     GLIST      Lists all nicknames in your group
13:42 -- NickServ (services@anope-services.intersocs):     IDENTIFY   Identify yourself with your password
13:42 -- NickServ (services@anope-services.intersocs):     ACCESS     Modify the list of authorized addresses
13:42 -- NickServ (services@anope-services.intersocs):     SET        Set options, including kill protection
13:42 -- NickServ (services@anope-services.intersocs):     DROP       Cancel the registration of a nickname
13:42 -- NickServ (services@anope-services.intersocs):     RECOVER    Kill another user who has taken your nick
13:42 -- NickServ (services@anope-services.intersocs):     RELEASE    Regain custody of your nick after RECOVER
13:42 -- NickServ (services@anope-services.intersocs):     GHOST      Disconnects a "ghost" IRC session using your nick
13:42 -- NickServ (services@anope-services.intersocs):     ALIST      List channels you have access on
13:42 -- NickServ (services@anope-services.intersocs):     INFO       Displays information about a given nickname
13:42 -- NickServ (services@anope-services.intersocs):     LIST       List all registered nicknames that match a given pattern
13:42 -- NickServ (services@anope-services.intersocs):     LOGOUT     Reverses the effect of the IDENTIFY command
13:42 -- NickServ (services@anope-services.intersocs):     STATUS     Returns the owner status of the given nickname
13:42 -- NickServ (services@anope-services.intersocs):     UPDATE     Updates your current status, i.e. it checks for new memos
13:42 -- NickServ (services@anope-services.intersocs):  
13:42 -- NickServ (services@anope-services.intersocs): NOTICE: This service is intended to provide a way for
13:42 -- NickServ (services@anope-services.intersocs): IRC users to ensure their identity is not compromised.
13:42 -- NickServ (services@anope-services.intersocs): It is NOT intended to facilitate "stealing" of
13:42 -- NickServ (services@anope-services.intersocs): nicknames or other malicious actions.  Abuse of NickServ
13:42 -- NickServ (services@anope-services.intersocs): will result in, at minimum, loss of the abused
13:42 -- NickServ (services@anope-services.intersocs): nickname(s).
`

**Comment by CSmartt** [comment]
`/m nickserv help` ^^ will tell you how to drop/reclaim/regist a nick

**Comment by butlerx** [comment]
this is also covered in our docs saying its run by trinity and telling you to run said command

**Comment by CSmartt** [comment]
Last word on this:
1. Use the help function
2. Wiki issue, this isn't an issue for our docs as it's a user process
