### ISSUE TITLE
add new sites to web section

### ISSUE THREAD

**Issue by butlerx** [redbrick/docs-old#89]
add instructions for deploying new sites
- [x] sistem
- [ ] admin blog

**Comment by theycallmemac** [comment]
These are both hugo sites on metharme correct?

**Comment by butlerx** [comment]
Yes

**Comment by butlerx** [comment]
Yes please consider mentioning where they should be in webtree how they are built with Hugo and possibly mention if they use the vserver template

**Comment by theycallmemac** [comment]
@butlerx they are built using hugo - but where? Hardly on metharme

**Comment by butlerx** [comment]
i previously manually built them on pyg, while this is a workable temp way of doing it a better way should be found, if hugo was manually installed on meth you could do it on meth. possible better solutions for this would be caddy or a systemd timer but they are out of scope of this issue

**Comment by theycallmemac** [comment]
Yes, out of scope indeed, I was just curious. I'll start some work on this tomorrow.

**Comment by butlerx** [comment]
given sistem is no longer hosted on redbrick i think we can consider this done

**Comment by butlerx** [comment]
i also think we can just drop this issue in favour of an issue in nix-config to build admin-blog

**Comment by theycallmemac** [comment]
I think you're right, this can be closed in favour of the nix-configs issues.
